# Generated by Django 5.0.6 on 2024-06-27 11:33

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0004_alter_page_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('header', '720x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
